name: Continuous Deployment Workflow

on:
  push: 
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:  #will set an environment variable accessible to our 'github action runner'
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build app
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Create and run Image
        run: gcloud builds submit --tag europe-north1-docker.pkg.dev/notely-469206/notely-ar-repo/notely:latest .

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run Database Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Google Cloud Run
        run: gcloud run deploy notely --image europe-north1-docker.pkg.dev/notely-469206/notely-ar-repo/notely:latest --region europe-north1 --allow-unauthenticated --project notely-469206 --max-instances=4

      
